"""empty message

Revision ID: 3a24e9099b46
Revises: 5b6896fc5e60
Create Date: 2020-08-15 15:26:01.612715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a24e9099b46'
down_revision = '5b6896fc5e60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column('title', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movie', 'title')
    # ### end Alembic commands ###
