"""empty message

Revision ID: 47658bba90c1
Revises: 3a24e9099b46
Create Date: 2020-08-15 15:38:59.384765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47658bba90c1'
down_revision = '3a24e9099b46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column('release_date',
                                     sa.Date(), nullable=False))
    op.drop_column('movie', 'relase_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column('relase_date', sa.DATE(),
                                     autoincrement=False,
                                     nullable=False))
    op.drop_column('movie', 'release_date')
    # ### end Alembic commands ###
